set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'tpope/vim-fugitive'

call vundle#end()
filetype plugin indent on

Plugin 'tomasiser/vim-code-dark'
Plugin 'majutsushi/tagbar'
Plugin 'Shougo/unite.vim'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'scrooloose/nerdcommenter'
Plugin 'airblade/vim-gitgutter'
Plugin 'octol/vim-cpp-enhanced-highlight'
Plugin 'godlygeek/tabular'
Plugin 'joe-skb7/cscope-maps'

" global preferences "
syntax on
colorscheme codedark
set nu
set t_Co=256
set mouse=a
set termencoding=utf-8
set clipboard=unnamedplus

" Remember info about open buffers on close
set viminfo^=%

" Backup
set undofile
set noswapfile
set nobackup

" Sounds
set noerrorbells
set novisualbell

" search
set smartcase
set ignorecase
set incsearch
set showmatch

" indention
set smartindent
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab

" highlighting
syntax on
set hlsearch

filetype indent on

set listchars=eol:$,tab:>-,trail:~,extends:>,precedes:<
set laststatus=2

set updatetime=100
